title: Play With Data
tagline: Exploring ideas through analytics
url: "https://robin-xie.github.io"  # 如果用自定义域名就改成你的域名
author:
  name: Robin Xie
  bio: "Business Analyst | Data Explorer | Passionate about storytelling with data"
  email: your@email.com

social:
  github: robin-xie
  linkedin: robin-xie
  email: your@email.com
